### ISSUE TITLE
Whenever I try to direct the program to a different folder, it does not process at all

### ISSUE THREAD

**Issue by bposch19972** [voicepaw/so-vits-svc-fork#276]
Whenever I try to direct the program to a different folder, it does not process at all. I don't know what is going on or how to fix it.

**Comment by 34j** [comment]
Need more info

**Comment by AntonPolyakin** [comment]
Same problem. 

By default the application is installed in `%APPDATA%\so-vits-svc-fork` (C:\Users\username\AppData\Roaming\so-vits-svc-fork), I want to install it on another disk because `C:\` is full.

At first I just tried to move the folder:
C:\Users\username\AppData\Roaming\so-vits-svc-fork\venv
to
D:\Programs\so-vits-svc-fork\venv.

by also changing the path in the activate.bat code:
`VIRTUAL_ENV=C:\old_directory\venv_name`
to
`VIRTUAL_ENV=C:\new_directory\venv_name`

But that didn't work

Then I tried changing the install.bat code:
```
@echo off

echo You can rerun this script to update the installation.

echo Moving to AppData\Roaming\so-vits-svc-fork...
mkdir "%APPDATA%\so-vits-svc-fork" >nul 2>&1
cd "%APPDATA%\so-vits-svc-fork"
```

This way:

```
@echo off

echo You can rerun this script to update the installation.

echo Moving to D:\Programs\so-vits-svc-fork...
mkdir "D:\Programs\so-vits-svc-fork" >nul 2>&1
cd "D:\Programs\so-vits-svc-fork"
```

None of this worked. If you can help me out, that would be great

**Comment by 34j** [comment]
I think it would be better to use pipx options instead of using the BAT file.
